name: Lint Code Base

on:
  push:
  pull_request:
  workflow_call:
    inputs:
      check-all:
        description: "Check entire codebase"
        required: false
        type: boolean
        default: true
      harden-runner:
        description: "Harden runner"
        required: false
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  linter:
    name: Lint Code Base
    runs-on: ubuntu-24.04
    steps:
      - uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        if: ${{ github.event_name != 'workflow_call' || inputs.harden-runner }}
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Lint codebase
        uses: super-linter/super-linter@61abc07d755095a68f4987d1c2c3d1d64408f1f9 # v8.5.0
        env:
          VALIDATE_ALL_CODEBASE: ${{ inputs.check-all }}
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_BIOME_LINT: false
          VALIDATE_GO: false
          VALIDATE_GO_MODULES: false
          VALIDATE_JSCPD: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_RUST_2015: false
          VALIDATE_RUST_2018: false
          VALIDATE_RUST_CLIPPY: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_INCLUDE: ".*go.mod"
