name: NPM Lint

on:
  workflow_call:
    inputs:
      working-directory:
        description: "Working directory"
        required: false
        type: string
        default: .
      harden-runner:
        description: "Harden runner"
        required: false
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  lint:
    name: NPM Lint
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: step-security/harden-runner@9ca718d3bf646d6534007c269a635b3e54cadf99 # v2.19.2
        if: ${{ inputs.harden-runner }}
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
          check-latest: true
      
      # Ensure npm version is at least 11.10.0 for the `npm config get min-release-age` command
      - name: Check npm version to be at least 11.10.0
        run: |
          npm_version=$(npm --version)
          required_version="11.10.0"

          if [ "$(printf '%s\n' "$required_version" "$npm_version" | sort -V | head -n1)" != "$required_version" ]; then
            echo "npm version $npm_version is less than required version $required_version"
            exit 1
          fi

      - name: Check min-release-age setting
        run: |
          # Check if .npmrc file exists
          if [ ! -f .npmrc ]; then
            echo ".npmrc file not found"
            exit 1
          else
            echo "✅ .npmrc file found"
          fi

          # Check if min-release-age line is present in npm config
          if ! grep -q "min-release-age" .npmrc; then
            echo "min-release-age setting is not present in npm config"
            exit 1
          else
            echo "✅ min-release-age setting found in npm config"
          fi

          # Check if min-release-age is set to greater than 0
          min_release_age=$(cat .npmrc | grep "min-release-age" | awk -F= '{print $2}' | tr -d ' ')
          if [ "$min_release_age" -le 0 ]; then
            echo "min-release-age setting is not set to greater than 0"
            exit 1
          else
            echo "✅ min-release-age setting is set to ${min_release_age}"
          fi

          # Check "before = date" exists
          before_date=$(npm config get before)
          if [ -z "$before_date" ]; then
            echo "before setting is not present in npm config"
            exit 1
          else
            echo "✅ before setting found in npm config with value: ${before_date}"
          fi

      - name: Install dependencies
        run: npm ci

      - name: Run npm run lint
        run: npm run lint
