name: Prettier

on:
  workflow_call:
    inputs:
      working-directory:
        description: "Working directory"
        required: false
        type: string
        default: .
      harden-runner:
        description: "Harden runner"
        required: false
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-26.04
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        if: ${{ inputs.harden-runner }}
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 26
          check-latest: true

      - name: Install dependencies
        run: npm ci

      - name: Run prettier
        run: |
          if [ -d "src" ]; then
            dir="src"
          elif [ -d "app" ]; then
            dir="app"
          else
            dir="."
          fi

          if [ -f ".prettierrc" ]; then
            npx prettier --config .prettierrc "${dir}/**/*.{ts,tsx,js,vue,html}" --check
          else
            npx prettier "${dir}/**/*.{ts,tsx,js,vue,html}" --check
          fi
