name: Release Drafter

on:
  workflow_call:
    inputs:
      harden-runner:
        description: "Harden runner"
        required: false
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  update:
    name: Update
    if: github.repository_owner == 'harryzcy'
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: ci-release-drafter
      cancel-in-progress: false
    runs-on: ubuntu-26.04
    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        if: ${{ inputs.harden-runner }}
        with:
          egress-policy: audit

      - name: Run release-drafter
        uses: release-drafter/release-drafter@34d80673e067bdc0c24568d3af899c216adcfaa9 # v7.7.0
        with:
          commitish: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
