name: Release Drafter

on:
  workflow_call:
    inputs:
      harden-runner:
        description: "Harden runner"
        required: false
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  update:
    name: Update
    if: github.repository_owner == 'harryzcy'
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: ci-release-drafter
      cancel-in-progress: false
    runs-on: ubuntu-24.04
    steps:
      - uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        if: ${{ inputs.harden-runner }}
        with:
          egress-policy: audit

      - name: Run release-drafter
        uses: release-drafter/release-drafter@3a7fb5c85b80b1dda66e1ccb94009adbbd32fce3 # v7.0.0
        with:
          commitish: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
