name: Release Drafter

on:
  workflow_call:
    inputs:
      harden-runner:
        description: "Harden runner"
        required: false
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  update:
    name: Update
    if: github.repository_owner == 'harryzcy'
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: ci-release-drafter
      cancel-in-progress: false
    runs-on: ubuntu-24.04
    steps:
      - uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        if: ${{ inputs.harden-runner }}
        with:
          egress-policy: audit

      - name: Run release-drafter
        uses: release-drafter/release-drafter@5de93583980a40bd78603b6dfdcda5b4df377b32 # v7.2.0
        with:
          commitish: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
