name: Renovate Config

on:
  push:
  pull_request:
  workflow_call:
    inputs:
      harden-runner:
        description: "Harden runner"
        required: false
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  renovate:
    name: Renovate Config
    runs-on: ubuntu-24.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        if: ${{ inputs.harden-runner }}
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 24
          check-latest: true

      - name: Check Renovate Config Syntax
        run: |
          npx --yes --package renovate@latest -- renovate-config-validator --strict
