name: Check Spelling

on:
  push:
  pull_request:
  workflow_call:
    inputs:
      harden-runner:
        description: "Harden runner"
        required: false
        type: boolean
        default: true
      config:
        description: "Path to typos config file"
        required: false
        type: string

permissions:
  contents: read

jobs:
  run:
    name: Spell Check
    runs-on: ubuntu-24.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        if: ${{ inputs.harden-runner || github.event_name != 'workflow_call' }}
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            objects.githubusercontent.com:443
            release-assets.githubusercontent.com:443

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check spelling
        uses: crate-ci/typos@cf5f1c29a8ac336af8568821ec41919923b05a83 # v1.45.1
        with:
          config: ${{ inputs.config }}
