name: Check Spelling

on:
  push:
  pull_request:
  workflow_call:
    inputs:
      harden-runner:
        description: "Harden runner"
        required: false
        type: boolean
        default: true
      config:
        description: "Path to typos config file"
        required: false
        type: string

permissions:
  contents: read

jobs:
  run:
    name: Spell Check
    runs-on: ubuntu-26.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        if: ${{ inputs.harden-runner || github.event_name != 'workflow_call' }}
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            objects.githubusercontent.com:443
            release-assets.githubusercontent.com:443

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check spelling
        uses: crate-ci/typos@4d9c206a77c041268485162b8e2579ad7a5cb9a3 # v1.50.0
        with:
          config: ${{ inputs.config }}
